# Code generated by sqlc. DO NOT EDIT.
# versions:
#   sqlc v1.30.0
import datetime
import pydantic


class Event(pydantic.BaseModel):
    id: int
    name: str
    created_at: pydantic.AwareDatetime
    updated_at: pydantic.AwareDatetime | None
    event_date: datetime.datetime | None
