# Code generated by sqlc. DO NOT EDIT.
# versions:
#   sqlc v1.30.0
# source: query.sql
from collections.abc import AsyncIterator, Iterator
from typing import cast

import sqlalchemy
import sqlalchemy.ext.asyncio
import sqlalchemy.orm

from db import models


CREATE_BOOK = """-- name: create_book \\:one
INSERT INTO books (
          title, status
) VALUES (
  :p1, :p2
) RETURNING id, title, status
"""


DELETE_BOOK = """-- name: delete_book \\:exec
DELETE FROM books
WHERE id = :p1
"""


GET_BOOK = """-- name: get_book \\:one
SELECT id, title, status FROM books
WHERE id = :p1 LIMIT 1
"""


LIST_BOOKS = """-- name: list_books \\:many
SELECT id, title, status FROM books
ORDER BY title
"""


class Querier[T: sqlalchemy.engine.Connection | sqlalchemy.orm.Session]:
    _conn: T

    def __init__(self, conn: T):
        self._conn = conn

    def create_book(self, *, title: str, status: models.BookStatus | None) -> models.Book | None:
        row = self._conn.execute(sqlalchemy.text(CREATE_BOOK), {"p1": title, "p2": status}).first()
        if row is None:
            return None
        return models.Book(
            id=cast(int, row[0]),
            title=cast(str, row[1]),
            status=cast(models.BookStatus | None, row[2]),
        )

    def delete_book(self, *, id: int) -> None:
        _ = self._conn.execute(sqlalchemy.text(DELETE_BOOK), {"p1": id})

    def get_book(self, *, id: int) -> models.Book | None:
        row = self._conn.execute(sqlalchemy.text(GET_BOOK), {"p1": id}).first()
        if row is None:
            return None
        return models.Book(
            id=cast(int, row[0]),
            title=cast(str, row[1]),
            status=cast(models.BookStatus | None, row[2]),
        )

    def list_books(self) -> Iterator[models.Book]:
        result = self._conn.execute(sqlalchemy.text(LIST_BOOKS))
        for row in result:
            yield models.Book(
                id=cast(int, row[0]),
                title=cast(str, row[1]),
                status=cast(models.BookStatus | None, row[2]),
            )


class AsyncQuerier[T: sqlalchemy.ext.asyncio.AsyncConnection | sqlalchemy.ext.asyncio.AsyncSession]:
    _conn: T

    def __init__(self, conn: T):
        self._conn = conn

    async def create_book(self, *, title: str, status: models.BookStatus | None) -> models.Book | None:
        row = (await self._conn.execute(sqlalchemy.text(CREATE_BOOK), {"p1": title, "p2": status})).first()
        if row is None:
            return None
        return models.Book(
            id=cast(int, row[0]),
            title=cast(str, row[1]),
            status=cast(models.BookStatus | None, row[2]),
        )

    async def delete_book(self, *, id: int) -> None:
        _ = await self._conn.execute(sqlalchemy.text(DELETE_BOOK), {"p1": id})

    async def get_book(self, *, id: int) -> models.Book | None:
        row = (await self._conn.execute(sqlalchemy.text(GET_BOOK), {"p1": id})).first()
        if row is None:
            return None
        return models.Book(
            id=cast(int, row[0]),
            title=cast(str, row[1]),
            status=cast(models.BookStatus | None, row[2]),
        )

    async def list_books(self) -> AsyncIterator[models.Book]:
        result = await self._conn.stream(sqlalchemy.text(LIST_BOOKS))
        async for row in result:
            yield models.Book(
                id=cast(int, row[0]),
                title=cast(str, row[1]),
                status=cast(models.BookStatus | None, row[2]),
            )
