# Code generated by sqlc. DO NOT EDIT.
# versions:
#   sqlc v1.30.0
import pydantic
from typing import Optional


class Author(pydantic.BaseModel):
    id: int
    name: str
    bio: Optional[str]


class Book(pydantic.BaseModel):
    id: int
    author_id: int
    title: str
    isbn: Optional[str]
