# Code generated by sqlc. DO NOT EDIT.
# versions:
#   sqlc v1.30.0
import pydantic


class Author(pydantic.BaseModel):
    id: int
    name: str
    bio: str | None


class Book(pydantic.BaseModel):
    id: int
    author_id: int
    title: str
    isbn: str | None
