# Code generated by sqlc. DO NOT EDIT.
# versions:
#   sqlc v1.30.0
# source: query.sql
from collections.abc import Iterator
import pydantic
from typing import cast

import sqlalchemy
import sqlalchemy.orm

from python import models


GET_BOOK_WITH_AUTHOR = """-- name: get_book_with_author \\:one
SELECT
    books.id, books.author_id, books.title, books.isbn,
    authors.id, authors.name, authors.bio
FROM books
JOIN authors ON books.author_id = authors.id
WHERE books.id = :p1
"""


class GetBookWithAuthorRow(pydantic.BaseModel):
    books: models.Book
    authors: models.Author


LIST_BOOKS_WITH_AUTHORS = """-- name: list_books_with_authors \\:many
SELECT
    books.id, books.author_id, books.title, books.isbn,
    authors.id, authors.name, authors.bio
FROM books
JOIN authors ON books.author_id = authors.id
ORDER BY books.title
"""


class ListBooksWithAuthorsRow(pydantic.BaseModel):
    books: models.Book
    authors: models.Author


class Querier[T: sqlalchemy.engine.Connection | sqlalchemy.orm.Session]:
    _conn: T

    def __init__(self, conn: T):
        self._conn = conn

    def get_book_with_author(self, *, id: int) -> GetBookWithAuthorRow | None:
        row = self._conn.execute(sqlalchemy.text(GET_BOOK_WITH_AUTHOR), {"p1": id}).first()
        if row is None:
            return None
        return GetBookWithAuthorRow(
            books=models.Book(
                id=cast(int, row[0]),
                author_id=cast(int, row[1]),
                title=cast(str, row[2]),
                isbn=cast(str | None, row[3]),
            ),
            authors=models.Author(
                id=cast(int, row[4]),
                name=cast(str, row[5]),
                bio=cast(str | None, row[6]),
            ),
        )

    def list_books_with_authors(self) -> Iterator[ListBooksWithAuthorsRow]:
        result = self._conn.execute(sqlalchemy.text(LIST_BOOKS_WITH_AUTHORS))
        for row in result:
            yield ListBooksWithAuthorsRow(
                books=models.Book(
                    id=cast(int, row[0]),
                    author_id=cast(int, row[1]),
                    title=cast(str, row[2]),
                    isbn=cast(str | None, row[3]),
                ),
                authors=models.Author(
                    id=cast(int, row[4]),
                    name=cast(str, row[5]),
                    bio=cast(str | None, row[6]),
                ),
            )
