# Code generated by sqlc. DO NOT EDIT.
# versions:
#   sqlc v1.30.0
# source: query.sql
import pydantic
from typing import Iterator

import sqlalchemy
import sqlalchemy.orm

from python import models


GET_BOOK_WITH_AUTHOR = """-- name: get_book_with_author \\:one
SELECT
    books.id, books.author_id, books.title, books.isbn,
    authors.id, authors.name, authors.bio
FROM books
JOIN authors ON books.author_id = authors.id
WHERE books.id = :p1
"""


class GetBookWithAuthorRow(pydantic.BaseModel):
    books: models.Book
    authors: models.Author


LIST_BOOKS_WITH_AUTHORS = """-- name: list_books_with_authors \\:many
SELECT
    books.id, books.author_id, books.title, books.isbn,
    authors.id, authors.name, authors.bio
FROM books
JOIN authors ON books.author_id = authors.id
ORDER BY books.title
"""


class ListBooksWithAuthorsRow(pydantic.BaseModel):
    books: models.Book
    authors: models.Author


class Querier:
    def __init__(self, conn: sqlalchemy.engine.Connection | sqlalchemy.orm.Session):
        self._conn = conn

    def get_book_with_author(self, *, id: int) -> GetBookWithAuthorRow | None:
        row = self._conn.execute(sqlalchemy.text(GET_BOOK_WITH_AUTHOR), {"p1": id}).first()
        if row is None:
            return None
        return GetBookWithAuthorRow(
            books=models.Book(
                id=row[0],
                author_id=row[1],
                title=row[2],
                isbn=row[3],
            ),
            authors=models.Author(
                id=row[4],
                name=row[5],
                bio=row[6],
            ),
        )

    def list_books_with_authors(self) -> Iterator[ListBooksWithAuthorsRow]:
        result = self._conn.execute(sqlalchemy.text(LIST_BOOKS_WITH_AUTHORS))
        for row in result:
            yield ListBooksWithAuthorsRow(
                books=models.Book(
                    id=row[0],
                    author_id=row[1],
                    title=row[2],
                    isbn=row[3],
                ),
                authors=models.Author(
                    id=row[4],
                    name=row[5],
                    bio=row[6],
                ),
            )
