// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v6.32.1
// source: ast/ast.proto

package ast

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Node struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Types that are valid to be assigned to Node:
	//
	//	*Node_ClassDef
	//	*Node_Import
	//	*Node_ImportFrom
	//	*Node_Module
	//	*Node_Alias
	//	*Node_AnnAssign
	//	*Node_Name
	//	*Node_Subscript
	//	*Node_Attribute
	//	*Node_Constant
	//	*Node_Assign
	//	*Node_Comment
	//	*Node_Expr
	//	*Node_Call
	//	*Node_FunctionDef
	//	*Node_Arg
	//	*Node_Arguments
	//	*Node_AsyncFunctionDef
	//	*Node_Pass
	//	*Node_Dict
	//	*Node_If
	//	*Node_Compare
	//	*Node_Return
	//	*Node_Is
	//	*Node_Keyword
	//	*Node_Yield
	//	*Node_For
	//	*Node_Await
	//	*Node_AsyncFor
	//	*Node_ImportGroup
	//	*Node_BinOp
	//	*Node_BitOr
	Node          isNode_Node `protobuf_oneof:"node"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Node) Reset() {
	*x = Node{}
	mi := &file_ast_ast_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Node) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Node) ProtoMessage() {}

func (x *Node) ProtoReflect() protoreflect.Message {
	mi := &file_ast_ast_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Node.ProtoReflect.Descriptor instead.
func (*Node) Descriptor() ([]byte, []int) {
	return file_ast_ast_proto_rawDescGZIP(), []int{0}
}

func (x *Node) GetNode() isNode_Node {
	if x != nil {
		return x.Node
	}
	return nil
}

func (x *Node) GetClassDef() *ClassDef {
	if x != nil {
		if x, ok := x.Node.(*Node_ClassDef); ok {
			return x.ClassDef
		}
	}
	return nil
}

func (x *Node) GetImport() *Import {
	if x != nil {
		if x, ok := x.Node.(*Node_Import); ok {
			return x.Import
		}
	}
	return nil
}

func (x *Node) GetImportFrom() *ImportFrom {
	if x != nil {
		if x, ok := x.Node.(*Node_ImportFrom); ok {
			return x.ImportFrom
		}
	}
	return nil
}

func (x *Node) GetModule() *Module {
	if x != nil {
		if x, ok := x.Node.(*Node_Module); ok {
			return x.Module
		}
	}
	return nil
}

func (x *Node) GetAlias() *Alias {
	if x != nil {
		if x, ok := x.Node.(*Node_Alias); ok {
			return x.Alias
		}
	}
	return nil
}

func (x *Node) GetAnnAssign() *AnnAssign {
	if x != nil {
		if x, ok := x.Node.(*Node_AnnAssign); ok {
			return x.AnnAssign
		}
	}
	return nil
}

func (x *Node) GetName() *Name {
	if x != nil {
		if x, ok := x.Node.(*Node_Name); ok {
			return x.Name
		}
	}
	return nil
}

func (x *Node) GetSubscript() *Subscript {
	if x != nil {
		if x, ok := x.Node.(*Node_Subscript); ok {
			return x.Subscript
		}
	}
	return nil
}

func (x *Node) GetAttribute() *Attribute {
	if x != nil {
		if x, ok := x.Node.(*Node_Attribute); ok {
			return x.Attribute
		}
	}
	return nil
}

func (x *Node) GetConstant() *Constant {
	if x != nil {
		if x, ok := x.Node.(*Node_Constant); ok {
			return x.Constant
		}
	}
	return nil
}

func (x *Node) GetAssign() *Assign {
	if x != nil {
		if x, ok := x.Node.(*Node_Assign); ok {
			return x.Assign
		}
	}
	return nil
}

func (x *Node) GetComment() *Comment {
	if x != nil {
		if x, ok := x.Node.(*Node_Comment); ok {
			return x.Comment
		}
	}
	return nil
}

func (x *Node) GetExpr() *Expr {
	if x != nil {
		if x, ok := x.Node.(*Node_Expr); ok {
			return x.Expr
		}
	}
	return nil
}

func (x *Node) GetCall() *Call {
	if x != nil {
		if x, ok := x.Node.(*Node_Call); ok {
			return x.Call
		}
	}
	return nil
}

func (x *Node) GetFunctionDef() *FunctionDef {
	if x != nil {
		if x, ok := x.Node.(*Node_FunctionDef); ok {
			return x.FunctionDef
		}
	}
	return nil
}

func (x *Node) GetArg() *Arg {
	if x != nil {
		if x, ok := x.Node.(*Node_Arg); ok {
			return x.Arg
		}
	}
	return nil
}

func (x *Node) GetArguments() *Arguments {
	if x != nil {
		if x, ok := x.Node.(*Node_Arguments); ok {
			return x.Arguments
		}
	}
	return nil
}

func (x *Node) GetAsyncFunctionDef() *AsyncFunctionDef {
	if x != nil {
		if x, ok := x.Node.(*Node_AsyncFunctionDef); ok {
			return x.AsyncFunctionDef
		}
	}
	return nil
}

func (x *Node) GetPass() *Pass {
	if x != nil {
		if x, ok := x.Node.(*Node_Pass); ok {
			return x.Pass
		}
	}
	return nil
}

func (x *Node) GetDict() *Dict {
	if x != nil {
		if x, ok := x.Node.(*Node_Dict); ok {
			return x.Dict
		}
	}
	return nil
}

func (x *Node) GetIf() *If {
	if x != nil {
		if x, ok := x.Node.(*Node_If); ok {
			return x.If
		}
	}
	return nil
}

func (x *Node) GetCompare() *Compare {
	if x != nil {
		if x, ok := x.Node.(*Node_Compare); ok {
			return x.Compare
		}
	}
	return nil
}

func (x *Node) GetReturn() *Return {
	if x != nil {
		if x, ok := x.Node.(*Node_Return); ok {
			return x.Return
		}
	}
	return nil
}

func (x *Node) GetIs() *Is {
	if x != nil {
		if x, ok := x.Node.(*Node_Is); ok {
			return x.Is
		}
	}
	return nil
}

func (x *Node) GetKeyword() *Keyword {
	if x != nil {
		if x, ok := x.Node.(*Node_Keyword); ok {
			return x.Keyword
		}
	}
	return nil
}

func (x *Node) GetYield() *Yield {
	if x != nil {
		if x, ok := x.Node.(*Node_Yield); ok {
			return x.Yield
		}
	}
	return nil
}

func (x *Node) GetFor() *For {
	if x != nil {
		if x, ok := x.Node.(*Node_For); ok {
			return x.For
		}
	}
	return nil
}

func (x *Node) GetAwait() *Await {
	if x != nil {
		if x, ok := x.Node.(*Node_Await); ok {
			return x.Await
		}
	}
	return nil
}

func (x *Node) GetAsyncFor() *AsyncFor {
	if x != nil {
		if x, ok := x.Node.(*Node_AsyncFor); ok {
			return x.AsyncFor
		}
	}
	return nil
}

func (x *Node) GetImportGroup() *ImportGroup {
	if x != nil {
		if x, ok := x.Node.(*Node_ImportGroup); ok {
			return x.ImportGroup
		}
	}
	return nil
}

func (x *Node) GetBinOp() *BinOp {
	if x != nil {
		if x, ok := x.Node.(*Node_BinOp); ok {
			return x.BinOp
		}
	}
	return nil
}

func (x *Node) GetBitOr() *BitOr {
	if x != nil {
		if x, ok := x.Node.(*Node_BitOr); ok {
			return x.BitOr
		}
	}
	return nil
}

type isNode_Node interface {
	isNode_Node()
}

type Node_ClassDef struct {
	ClassDef *ClassDef `protobuf:"bytes,1,opt,name=class_def,json=ClassDef,proto3,oneof"`
}

type Node_Import struct {
	Import *Import `protobuf:"bytes,2,opt,name=import,json=Import,proto3,oneof"`
}

type Node_ImportFrom struct {
	ImportFrom *ImportFrom `protobuf:"bytes,3,opt,name=import_from,json=ImportFrom,proto3,oneof"`
}

type Node_Module struct {
	Module *Module `protobuf:"bytes,4,opt,name=module,json=Module,proto3,oneof"`
}

type Node_Alias struct {
	Alias *Alias `protobuf:"bytes,5,opt,name=alias,json=Alias,proto3,oneof"`
}

type Node_AnnAssign struct {
	AnnAssign *AnnAssign `protobuf:"bytes,6,opt,name=ann_assign,json=AnnAssign,proto3,oneof"`
}

type Node_Name struct {
	Name *Name `protobuf:"bytes,7,opt,name=name,json=Name,proto3,oneof"`
}

type Node_Subscript struct {
	Subscript *Subscript `protobuf:"bytes,8,opt,name=subscript,json=Subscript,proto3,oneof"`
}

type Node_Attribute struct {
	Attribute *Attribute `protobuf:"bytes,9,opt,name=attribute,json=Attribute,proto3,oneof"`
}

type Node_Constant struct {
	Constant *Constant `protobuf:"bytes,10,opt,name=constant,json=Constant,proto3,oneof"`
}

type Node_Assign struct {
	Assign *Assign `protobuf:"bytes,11,opt,name=assign,json=Assign,proto3,oneof"`
}

type Node_Comment struct {
	Comment *Comment `protobuf:"bytes,12,opt,name=comment,json=Comment,proto3,oneof"`
}

type Node_Expr struct {
	Expr *Expr `protobuf:"bytes,13,opt,name=expr,json=Expr,proto3,oneof"`
}

type Node_Call struct {
	Call *Call `protobuf:"bytes,14,opt,name=call,json=Call,proto3,oneof"`
}

type Node_FunctionDef struct {
	FunctionDef *FunctionDef `protobuf:"bytes,15,opt,name=function_def,json=FunctionDef,proto3,oneof"`
}

type Node_Arg struct {
	Arg *Arg `protobuf:"bytes,16,opt,name=arg,json=Arg,proto3,oneof"`
}

type Node_Arguments struct {
	Arguments *Arguments `protobuf:"bytes,17,opt,name=arguments,json=Arguments,proto3,oneof"`
}

type Node_AsyncFunctionDef struct {
	AsyncFunctionDef *AsyncFunctionDef `protobuf:"bytes,18,opt,name=async_function_def,json=AsyncFunctionDef,proto3,oneof"`
}

type Node_Pass struct {
	Pass *Pass `protobuf:"bytes,19,opt,name=pass,json=Pass,proto3,oneof"`
}

type Node_Dict struct {
	Dict *Dict `protobuf:"bytes,20,opt,name=dict,json=Dict,proto3,oneof"`
}

type Node_If struct {
	If *If `protobuf:"bytes,21,opt,name=if,json=If,proto3,oneof"`
}

type Node_Compare struct {
	Compare *Compare `protobuf:"bytes,22,opt,name=compare,json=Compare,proto3,oneof"`
}

type Node_Return struct {
	Return *Return `protobuf:"bytes,23,opt,name=return,json=Return,proto3,oneof"`
}

type Node_Is struct {
	Is *Is `protobuf:"bytes,24,opt,name=is,json=Is,proto3,oneof"`
}

type Node_Keyword struct {
	Keyword *Keyword `protobuf:"bytes,25,opt,name=keyword,json=Keyword,proto3,oneof"`
}

type Node_Yield struct {
	Yield *Yield `protobuf:"bytes,26,opt,name=yield,json=Yield,proto3,oneof"`
}

type Node_For struct {
	For *For `protobuf:"bytes,27,opt,name=for,json=For,proto3,oneof"`
}

type Node_Await struct {
	Await *Await `protobuf:"bytes,28,opt,name=await,json=Await,proto3,oneof"`
}

type Node_AsyncFor struct {
	AsyncFor *AsyncFor `protobuf:"bytes,29,opt,name=async_for,json=AsyncFor,proto3,oneof"`
}

type Node_ImportGroup struct {
	ImportGroup *ImportGroup `protobuf:"bytes,30,opt,name=import_group,json=ImportGroup,proto3,oneof"`
}

type Node_BinOp struct {
	BinOp *BinOp `protobuf:"bytes,31,opt,name=bin_op,json=BinOp,proto3,oneof"`
}

type Node_BitOr struct {
	BitOr *BitOr `protobuf:"bytes,32,opt,name=bit_or,json=BitOr,proto3,oneof"`
}

func (*Node_ClassDef) isNode_Node() {}

func (*Node_Import) isNode_Node() {}

func (*Node_ImportFrom) isNode_Node() {}

func (*Node_Module) isNode_Node() {}

func (*Node_Alias) isNode_Node() {}

func (*Node_AnnAssign) isNode_Node() {}

func (*Node_Name) isNode_Node() {}

func (*Node_Subscript) isNode_Node() {}

func (*Node_Attribute) isNode_Node() {}

func (*Node_Constant) isNode_Node() {}

func (*Node_Assign) isNode_Node() {}

func (*Node_Comment) isNode_Node() {}

func (*Node_Expr) isNode_Node() {}

func (*Node_Call) isNode_Node() {}

func (*Node_FunctionDef) isNode_Node() {}

func (*Node_Arg) isNode_Node() {}

func (*Node_Arguments) isNode_Node() {}

func (*Node_AsyncFunctionDef) isNode_Node() {}

func (*Node_Pass) isNode_Node() {}

func (*Node_Dict) isNode_Node() {}

func (*Node_If) isNode_Node() {}

func (*Node_Compare) isNode_Node() {}

func (*Node_Return) isNode_Node() {}

func (*Node_Is) isNode_Node() {}

func (*Node_Keyword) isNode_Node() {}

func (*Node_Yield) isNode_Node() {}

func (*Node_For) isNode_Node() {}

func (*Node_Await) isNode_Node() {}

func (*Node_AsyncFor) isNode_Node() {}

func (*Node_ImportGroup) isNode_Node() {}

func (*Node_BinOp) isNode_Node() {}

func (*Node_BitOr) isNode_Node() {}

type Alias struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Alias) Reset() {
	*x = Alias{}
	mi := &file_ast_ast_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Alias) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Alias) ProtoMessage() {}

func (x *Alias) ProtoReflect() protoreflect.Message {
	mi := &file_ast_ast_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Alias.ProtoReflect.Descriptor instead.
func (*Alias) Descriptor() ([]byte, []int) {
	return file_ast_ast_proto_rawDescGZIP(), []int{1}
}

func (x *Alias) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

type Await struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Value         *Node                  `protobuf:"bytes,1,opt,name=value,proto3" json:"value,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Await) Reset() {
	*x = Await{}
	mi := &file_ast_ast_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Await) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Await) ProtoMessage() {}

func (x *Await) ProtoReflect() protoreflect.Message {
	mi := &file_ast_ast_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Await.ProtoReflect.Descriptor instead.
func (*Await) Descriptor() ([]byte, []int) {
	return file_ast_ast_proto_rawDescGZIP(), []int{2}
}

func (x *Await) GetValue() *Node {
	if x != nil {
		return x.Value
	}
	return nil
}

type BinOp struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Left          *Node                  `protobuf:"bytes,1,opt,name=left,proto3" json:"left,omitempty"`
	Op            *Node                  `protobuf:"bytes,2,opt,name=op,proto3" json:"op,omitempty"`
	Right         *Node                  `protobuf:"bytes,3,opt,name=right,proto3" json:"right,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *BinOp) Reset() {
	*x = BinOp{}
	mi := &file_ast_ast_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BinOp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BinOp) ProtoMessage() {}

func (x *BinOp) ProtoReflect() protoreflect.Message {
	mi := &file_ast_ast_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BinOp.ProtoReflect.Descriptor instead.
func (*BinOp) Descriptor() ([]byte, []int) {
	return file_ast_ast_proto_rawDescGZIP(), []int{3}
}

func (x *BinOp) GetLeft() *Node {
	if x != nil {
		return x.Left
	}
	return nil
}

func (x *BinOp) GetOp() *Node {
	if x != nil {
		return x.Op
	}
	return nil
}

func (x *BinOp) GetRight() *Node {
	if x != nil {
		return x.Right
	}
	return nil
}

type BitOr struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *BitOr) Reset() {
	*x = BitOr{}
	mi := &file_ast_ast_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BitOr) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BitOr) ProtoMessage() {}

func (x *BitOr) ProtoReflect() protoreflect.Message {
	mi := &file_ast_ast_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BitOr.ProtoReflect.Descriptor instead.
func (*BitOr) Descriptor() ([]byte, []int) {
	return file_ast_ast_proto_rawDescGZIP(), []int{4}
}

type Attribute struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Value         *Node                  `protobuf:"bytes,1,opt,name=value,proto3" json:"value,omitempty"`
	Attr          string                 `protobuf:"bytes,2,opt,name=attr,proto3" json:"attr,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Attribute) Reset() {
	*x = Attribute{}
	mi := &file_ast_ast_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Attribute) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Attribute) ProtoMessage() {}

func (x *Attribute) ProtoReflect() protoreflect.Message {
	mi := &file_ast_ast_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Attribute.ProtoReflect.Descriptor instead.
func (*Attribute) Descriptor() ([]byte, []int) {
	return file_ast_ast_proto_rawDescGZIP(), []int{5}
}

func (x *Attribute) GetValue() *Node {
	if x != nil {
		return x.Value
	}
	return nil
}

func (x *Attribute) GetAttr() string {
	if x != nil {
		return x.Attr
	}
	return ""
}

type AnnAssign struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Target        *Name                  `protobuf:"bytes,1,opt,name=target,proto3" json:"target,omitempty"`
	Annotation    *Node                  `protobuf:"bytes,2,opt,name=annotation,proto3" json:"annotation,omitempty"`
	Simple        int32                  `protobuf:"varint,3,opt,name=simple,proto3" json:"simple,omitempty"`
	Comment       string                 `protobuf:"bytes,4,opt,name=Comment,json=comment,proto3" json:"Comment,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AnnAssign) Reset() {
	*x = AnnAssign{}
	mi := &file_ast_ast_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AnnAssign) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AnnAssign) ProtoMessage() {}

func (x *AnnAssign) ProtoReflect() protoreflect.Message {
	mi := &file_ast_ast_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AnnAssign.ProtoReflect.Descriptor instead.
func (*AnnAssign) Descriptor() ([]byte, []int) {
	return file_ast_ast_proto_rawDescGZIP(), []int{6}
}

func (x *AnnAssign) GetTarget() *Name {
	if x != nil {
		return x.Target
	}
	return nil
}

func (x *AnnAssign) GetAnnotation() *Node {
	if x != nil {
		return x.Annotation
	}
	return nil
}

func (x *AnnAssign) GetSimple() int32 {
	if x != nil {
		return x.Simple
	}
	return 0
}

func (x *AnnAssign) GetComment() string {
	if x != nil {
		return x.Comment
	}
	return ""
}

type Arg struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Arg           string                 `protobuf:"bytes,1,opt,name=arg,proto3" json:"arg,omitempty"`
	Annotation    *Node                  `protobuf:"bytes,2,opt,name=annotation,proto3" json:"annotation,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Arg) Reset() {
	*x = Arg{}
	mi := &file_ast_ast_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Arg) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Arg) ProtoMessage() {}

func (x *Arg) ProtoReflect() protoreflect.Message {
	mi := &file_ast_ast_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Arg.ProtoReflect.Descriptor instead.
func (*Arg) Descriptor() ([]byte, []int) {
	return file_ast_ast_proto_rawDescGZIP(), []int{7}
}

func (x *Arg) GetArg() string {
	if x != nil {
		return x.Arg
	}
	return ""
}

func (x *Arg) GetAnnotation() *Node {
	if x != nil {
		return x.Annotation
	}
	return nil
}

type Arguments struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Args          []*Arg                 `protobuf:"bytes,1,rep,name=args,proto3" json:"args,omitempty"`
	KwOnlyArgs    []*Arg                 `protobuf:"bytes,2,rep,name=kw_only_args,json=kwonlyargs,proto3" json:"kw_only_args,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Arguments) Reset() {
	*x = Arguments{}
	mi := &file_ast_ast_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Arguments) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Arguments) ProtoMessage() {}

func (x *Arguments) ProtoReflect() protoreflect.Message {
	mi := &file_ast_ast_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Arguments.ProtoReflect.Descriptor instead.
func (*Arguments) Descriptor() ([]byte, []int) {
	return file_ast_ast_proto_rawDescGZIP(), []int{8}
}

func (x *Arguments) GetArgs() []*Arg {
	if x != nil {
		return x.Args
	}
	return nil
}

func (x *Arguments) GetKwOnlyArgs() []*Arg {
	if x != nil {
		return x.KwOnlyArgs
	}
	return nil
}

type AsyncFor struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Target        *Node                  `protobuf:"bytes,1,opt,name=target,proto3" json:"target,omitempty"`
	Iter          *Node                  `protobuf:"bytes,2,opt,name=iter,proto3" json:"iter,omitempty"`
	Body          []*Node                `protobuf:"bytes,3,rep,name=body,proto3" json:"body,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AsyncFor) Reset() {
	*x = AsyncFor{}
	mi := &file_ast_ast_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AsyncFor) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AsyncFor) ProtoMessage() {}

func (x *AsyncFor) ProtoReflect() protoreflect.Message {
	mi := &file_ast_ast_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AsyncFor.ProtoReflect.Descriptor instead.
func (*AsyncFor) Descriptor() ([]byte, []int) {
	return file_ast_ast_proto_rawDescGZIP(), []int{9}
}

func (x *AsyncFor) GetTarget() *Node {
	if x != nil {
		return x.Target
	}
	return nil
}

func (x *AsyncFor) GetIter() *Node {
	if x != nil {
		return x.Iter
	}
	return nil
}

func (x *AsyncFor) GetBody() []*Node {
	if x != nil {
		return x.Body
	}
	return nil
}

type AsyncFunctionDef struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Args          *Arguments             `protobuf:"bytes,2,opt,name=Args,json=args,proto3" json:"Args,omitempty"`
	Body          []*Node                `protobuf:"bytes,3,rep,name=body,proto3" json:"body,omitempty"`
	Returns       *Node                  `protobuf:"bytes,4,opt,name=returns,proto3" json:"returns,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AsyncFunctionDef) Reset() {
	*x = AsyncFunctionDef{}
	mi := &file_ast_ast_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AsyncFunctionDef) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AsyncFunctionDef) ProtoMessage() {}

func (x *AsyncFunctionDef) ProtoReflect() protoreflect.Message {
	mi := &file_ast_ast_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AsyncFunctionDef.ProtoReflect.Descriptor instead.
func (*AsyncFunctionDef) Descriptor() ([]byte, []int) {
	return file_ast_ast_proto_rawDescGZIP(), []int{10}
}

func (x *AsyncFunctionDef) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *AsyncFunctionDef) GetArgs() *Arguments {
	if x != nil {
		return x.Args
	}
	return nil
}

func (x *AsyncFunctionDef) GetBody() []*Node {
	if x != nil {
		return x.Body
	}
	return nil
}

func (x *AsyncFunctionDef) GetReturns() *Node {
	if x != nil {
		return x.Returns
	}
	return nil
}

type Assign struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Targets       []*Node                `protobuf:"bytes,1,rep,name=targets,proto3" json:"targets,omitempty"`
	Value         *Node                  `protobuf:"bytes,2,opt,name=value,proto3" json:"value,omitempty"`
	Comment       string                 `protobuf:"bytes,3,opt,name=Comment,json=comment,proto3" json:"Comment,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Assign) Reset() {
	*x = Assign{}
	mi := &file_ast_ast_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Assign) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Assign) ProtoMessage() {}

func (x *Assign) ProtoReflect() protoreflect.Message {
	mi := &file_ast_ast_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Assign.ProtoReflect.Descriptor instead.
func (*Assign) Descriptor() ([]byte, []int) {
	return file_ast_ast_proto_rawDescGZIP(), []int{11}
}

func (x *Assign) GetTargets() []*Node {
	if x != nil {
		return x.Targets
	}
	return nil
}

func (x *Assign) GetValue() *Node {
	if x != nil {
		return x.Value
	}
	return nil
}

func (x *Assign) GetComment() string {
	if x != nil {
		return x.Comment
	}
	return ""
}

type Call struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Func          *Node                  `protobuf:"bytes,1,opt,name=func,proto3" json:"func,omitempty"`
	Args          []*Node                `protobuf:"bytes,2,rep,name=args,proto3" json:"args,omitempty"`
	Keywords      []*Keyword             `protobuf:"bytes,3,rep,name=keywords,proto3" json:"keywords,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Call) Reset() {
	*x = Call{}
	mi := &file_ast_ast_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Call) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Call) ProtoMessage() {}

func (x *Call) ProtoReflect() protoreflect.Message {
	mi := &file_ast_ast_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Call.ProtoReflect.Descriptor instead.
func (*Call) Descriptor() ([]byte, []int) {
	return file_ast_ast_proto_rawDescGZIP(), []int{12}
}

func (x *Call) GetFunc() *Node {
	if x != nil {
		return x.Func
	}
	return nil
}

func (x *Call) GetArgs() []*Node {
	if x != nil {
		return x.Args
	}
	return nil
}

func (x *Call) GetKeywords() []*Keyword {
	if x != nil {
		return x.Keywords
	}
	return nil
}

type ClassDef struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Bases         []*Node                `protobuf:"bytes,2,rep,name=bases,proto3" json:"bases,omitempty"`
	Keywords      []*Node                `protobuf:"bytes,3,rep,name=keywords,proto3" json:"keywords,omitempty"`
	Body          []*Node                `protobuf:"bytes,4,rep,name=body,proto3" json:"body,omitempty"`
	DecoratorList []*Node                `protobuf:"bytes,5,rep,name=decorator_list,proto3" json:"decorator_list,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ClassDef) Reset() {
	*x = ClassDef{}
	mi := &file_ast_ast_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ClassDef) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ClassDef) ProtoMessage() {}

func (x *ClassDef) ProtoReflect() protoreflect.Message {
	mi := &file_ast_ast_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ClassDef.ProtoReflect.Descriptor instead.
func (*ClassDef) Descriptor() ([]byte, []int) {
	return file_ast_ast_proto_rawDescGZIP(), []int{13}
}

func (x *ClassDef) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *ClassDef) GetBases() []*Node {
	if x != nil {
		return x.Bases
	}
	return nil
}

func (x *ClassDef) GetKeywords() []*Node {
	if x != nil {
		return x.Keywords
	}
	return nil
}

func (x *ClassDef) GetBody() []*Node {
	if x != nil {
		return x.Body
	}
	return nil
}

func (x *ClassDef) GetDecoratorList() []*Node {
	if x != nil {
		return x.DecoratorList
	}
	return nil
}

// The Python ast module does not parse comments. It's not clear if this is the
// best way to support them in the AST
type Comment struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Text          string                 `protobuf:"bytes,1,opt,name=text,proto3" json:"text,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Comment) Reset() {
	*x = Comment{}
	mi := &file_ast_ast_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Comment) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Comment) ProtoMessage() {}

func (x *Comment) ProtoReflect() protoreflect.Message {
	mi := &file_ast_ast_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Comment.ProtoReflect.Descriptor instead.
func (*Comment) Descriptor() ([]byte, []int) {
	return file_ast_ast_proto_rawDescGZIP(), []int{14}
}

func (x *Comment) GetText() string {
	if x != nil {
		return x.Text
	}
	return ""
}

type Compare struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Left          *Node                  `protobuf:"bytes,1,opt,name=left,proto3" json:"left,omitempty"`
	Ops           []*Node                `protobuf:"bytes,2,rep,name=ops,proto3" json:"ops,omitempty"`
	Comparators   []*Node                `protobuf:"bytes,3,rep,name=comparators,proto3" json:"comparators,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Compare) Reset() {
	*x = Compare{}
	mi := &file_ast_ast_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Compare) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Compare) ProtoMessage() {}

func (x *Compare) ProtoReflect() protoreflect.Message {
	mi := &file_ast_ast_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Compare.ProtoReflect.Descriptor instead.
func (*Compare) Descriptor() ([]byte, []int) {
	return file_ast_ast_proto_rawDescGZIP(), []int{15}
}

func (x *Compare) GetLeft() *Node {
	if x != nil {
		return x.Left
	}
	return nil
}

func (x *Compare) GetOps() []*Node {
	if x != nil {
		return x.Ops
	}
	return nil
}

func (x *Compare) GetComparators() []*Node {
	if x != nil {
		return x.Comparators
	}
	return nil
}

type Constant struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Types that are valid to be assigned to Value:
	//
	//	*Constant_Str
	//	*Constant_Int
	//	*Constant_None
	Value         isConstant_Value `protobuf_oneof:"value"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Constant) Reset() {
	*x = Constant{}
	mi := &file_ast_ast_proto_msgTypes[16]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Constant) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Constant) ProtoMessage() {}

func (x *Constant) ProtoReflect() protoreflect.Message {
	mi := &file_ast_ast_proto_msgTypes[16]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Constant.ProtoReflect.Descriptor instead.
func (*Constant) Descriptor() ([]byte, []int) {
	return file_ast_ast_proto_rawDescGZIP(), []int{16}
}

func (x *Constant) GetValue() isConstant_Value {
	if x != nil {
		return x.Value
	}
	return nil
}

func (x *Constant) GetStr() string {
	if x != nil {
		if x, ok := x.Value.(*Constant_Str); ok {
			return x.Str
		}
	}
	return ""
}

func (x *Constant) GetInt() int32 {
	if x != nil {
		if x, ok := x.Value.(*Constant_Int); ok {
			return x.Int
		}
	}
	return 0
}

func (x *Constant) GetNone() bool {
	if x != nil {
		if x, ok := x.Value.(*Constant_None); ok {
			return x.None
		}
	}
	return false
}

type isConstant_Value interface {
	isConstant_Value()
}

type Constant_Str struct {
	Str string `protobuf:"bytes,1,opt,name=str,json=string,proto3,oneof"`
}

type Constant_Int struct {
	Int int32 `protobuf:"varint,2,opt,name=int,proto3,oneof"`
}

type Constant_None struct {
	None bool `protobuf:"varint,3,opt,name=none,proto3,oneof"`
}

func (*Constant_Str) isConstant_Value() {}

func (*Constant_Int) isConstant_Value() {}

func (*Constant_None) isConstant_Value() {}

type Dict struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Keys          []*Node                `protobuf:"bytes,1,rep,name=keys,proto3" json:"keys,omitempty"`
	Values        []*Node                `protobuf:"bytes,2,rep,name=values,proto3" json:"values,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Dict) Reset() {
	*x = Dict{}
	mi := &file_ast_ast_proto_msgTypes[17]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Dict) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Dict) ProtoMessage() {}

func (x *Dict) ProtoReflect() protoreflect.Message {
	mi := &file_ast_ast_proto_msgTypes[17]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Dict.ProtoReflect.Descriptor instead.
func (*Dict) Descriptor() ([]byte, []int) {
	return file_ast_ast_proto_rawDescGZIP(), []int{17}
}

func (x *Dict) GetKeys() []*Node {
	if x != nil {
		return x.Keys
	}
	return nil
}

func (x *Dict) GetValues() []*Node {
	if x != nil {
		return x.Values
	}
	return nil
}

type Expr struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Value         *Node                  `protobuf:"bytes,1,opt,name=value,proto3" json:"value,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Expr) Reset() {
	*x = Expr{}
	mi := &file_ast_ast_proto_msgTypes[18]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Expr) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Expr) ProtoMessage() {}

func (x *Expr) ProtoReflect() protoreflect.Message {
	mi := &file_ast_ast_proto_msgTypes[18]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Expr.ProtoReflect.Descriptor instead.
func (*Expr) Descriptor() ([]byte, []int) {
	return file_ast_ast_proto_rawDescGZIP(), []int{18}
}

func (x *Expr) GetValue() *Node {
	if x != nil {
		return x.Value
	}
	return nil
}

type For struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Target        *Node                  `protobuf:"bytes,1,opt,name=target,proto3" json:"target,omitempty"`
	Iter          *Node                  `protobuf:"bytes,2,opt,name=iter,proto3" json:"iter,omitempty"`
	Body          []*Node                `protobuf:"bytes,3,rep,name=body,proto3" json:"body,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *For) Reset() {
	*x = For{}
	mi := &file_ast_ast_proto_msgTypes[19]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *For) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*For) ProtoMessage() {}

func (x *For) ProtoReflect() protoreflect.Message {
	mi := &file_ast_ast_proto_msgTypes[19]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use For.ProtoReflect.Descriptor instead.
func (*For) Descriptor() ([]byte, []int) {
	return file_ast_ast_proto_rawDescGZIP(), []int{19}
}

func (x *For) GetTarget() *Node {
	if x != nil {
		return x.Target
	}
	return nil
}

func (x *For) GetIter() *Node {
	if x != nil {
		return x.Iter
	}
	return nil
}

func (x *For) GetBody() []*Node {
	if x != nil {
		return x.Body
	}
	return nil
}

type FunctionDef struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Args          *Arguments             `protobuf:"bytes,2,opt,name=Args,json=args,proto3" json:"Args,omitempty"`
	Body          []*Node                `protobuf:"bytes,3,rep,name=body,proto3" json:"body,omitempty"`
	Returns       *Node                  `protobuf:"bytes,4,opt,name=returns,proto3" json:"returns,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *FunctionDef) Reset() {
	*x = FunctionDef{}
	mi := &file_ast_ast_proto_msgTypes[20]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FunctionDef) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FunctionDef) ProtoMessage() {}

func (x *FunctionDef) ProtoReflect() protoreflect.Message {
	mi := &file_ast_ast_proto_msgTypes[20]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FunctionDef.ProtoReflect.Descriptor instead.
func (*FunctionDef) Descriptor() ([]byte, []int) {
	return file_ast_ast_proto_rawDescGZIP(), []int{20}
}

func (x *FunctionDef) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *FunctionDef) GetArgs() *Arguments {
	if x != nil {
		return x.Args
	}
	return nil
}

func (x *FunctionDef) GetBody() []*Node {
	if x != nil {
		return x.Body
	}
	return nil
}

func (x *FunctionDef) GetReturns() *Node {
	if x != nil {
		return x.Returns
	}
	return nil
}

type If struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Test          *Node                  `protobuf:"bytes,1,opt,name=test,proto3" json:"test,omitempty"`
	Body          []*Node                `protobuf:"bytes,2,rep,name=body,proto3" json:"body,omitempty"`
	OrElse        []*Node                `protobuf:"bytes,3,rep,name=or_else,json=orelse,proto3" json:"or_else,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *If) Reset() {
	*x = If{}
	mi := &file_ast_ast_proto_msgTypes[21]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *If) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*If) ProtoMessage() {}

func (x *If) ProtoReflect() protoreflect.Message {
	mi := &file_ast_ast_proto_msgTypes[21]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use If.ProtoReflect.Descriptor instead.
func (*If) Descriptor() ([]byte, []int) {
	return file_ast_ast_proto_rawDescGZIP(), []int{21}
}

func (x *If) GetTest() *Node {
	if x != nil {
		return x.Test
	}
	return nil
}

func (x *If) GetBody() []*Node {
	if x != nil {
		return x.Body
	}
	return nil
}

func (x *If) GetOrElse() []*Node {
	if x != nil {
		return x.OrElse
	}
	return nil
}

type Import struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Names         []*Node                `protobuf:"bytes,1,rep,name=names,proto3" json:"names,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Import) Reset() {
	*x = Import{}
	mi := &file_ast_ast_proto_msgTypes[22]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Import) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Import) ProtoMessage() {}

func (x *Import) ProtoReflect() protoreflect.Message {
	mi := &file_ast_ast_proto_msgTypes[22]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Import.ProtoReflect.Descriptor instead.
func (*Import) Descriptor() ([]byte, []int) {
	return file_ast_ast_proto_rawDescGZIP(), []int{22}
}

func (x *Import) GetNames() []*Node {
	if x != nil {
		return x.Names
	}
	return nil
}

type ImportFrom struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Module        string                 `protobuf:"bytes,1,opt,name=module,proto3" json:"module,omitempty"`
	Names         []*Node                `protobuf:"bytes,2,rep,name=names,proto3" json:"names,omitempty"`
	Level         int32                  `protobuf:"varint,3,opt,name=level,proto3" json:"level,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ImportFrom) Reset() {
	*x = ImportFrom{}
	mi := &file_ast_ast_proto_msgTypes[23]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ImportFrom) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ImportFrom) ProtoMessage() {}

func (x *ImportFrom) ProtoReflect() protoreflect.Message {
	mi := &file_ast_ast_proto_msgTypes[23]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ImportFrom.ProtoReflect.Descriptor instead.
func (*ImportFrom) Descriptor() ([]byte, []int) {
	return file_ast_ast_proto_rawDescGZIP(), []int{23}
}

func (x *ImportFrom) GetModule() string {
	if x != nil {
		return x.Module
	}
	return ""
}

func (x *ImportFrom) GetNames() []*Node {
	if x != nil {
		return x.Names
	}
	return nil
}

func (x *ImportFrom) GetLevel() int32 {
	if x != nil {
		return x.Level
	}
	return 0
}

// Imports are always put at the top of the file, just after any module
// comments and docstrings, and before module globals and constants.
//
// Imports should be grouped in the following order:
//
//	Standard library imports.
//	Related third party imports.
//	Local application/library specific imports.
//
// You should put a blank line between each group of imports.
//
// https://www.python.org/dev/peps/pep-0008/#imports
type ImportGroup struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Imports       []*Node                `protobuf:"bytes,1,rep,name=imports,proto3" json:"imports,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ImportGroup) Reset() {
	*x = ImportGroup{}
	mi := &file_ast_ast_proto_msgTypes[24]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ImportGroup) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ImportGroup) ProtoMessage() {}

func (x *ImportGroup) ProtoReflect() protoreflect.Message {
	mi := &file_ast_ast_proto_msgTypes[24]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ImportGroup.ProtoReflect.Descriptor instead.
func (*ImportGroup) Descriptor() ([]byte, []int) {
	return file_ast_ast_proto_rawDescGZIP(), []int{24}
}

func (x *ImportGroup) GetImports() []*Node {
	if x != nil {
		return x.Imports
	}
	return nil
}

type Is struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Is) Reset() {
	*x = Is{}
	mi := &file_ast_ast_proto_msgTypes[25]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Is) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Is) ProtoMessage() {}

func (x *Is) ProtoReflect() protoreflect.Message {
	mi := &file_ast_ast_proto_msgTypes[25]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Is.ProtoReflect.Descriptor instead.
func (*Is) Descriptor() ([]byte, []int) {
	return file_ast_ast_proto_rawDescGZIP(), []int{25}
}

type Keyword struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Arg           string                 `protobuf:"bytes,1,opt,name=arg,proto3" json:"arg,omitempty"`
	Value         *Node                  `protobuf:"bytes,2,opt,name=value,proto3" json:"value,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Keyword) Reset() {
	*x = Keyword{}
	mi := &file_ast_ast_proto_msgTypes[26]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Keyword) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Keyword) ProtoMessage() {}

func (x *Keyword) ProtoReflect() protoreflect.Message {
	mi := &file_ast_ast_proto_msgTypes[26]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Keyword.ProtoReflect.Descriptor instead.
func (*Keyword) Descriptor() ([]byte, []int) {
	return file_ast_ast_proto_rawDescGZIP(), []int{26}
}

func (x *Keyword) GetArg() string {
	if x != nil {
		return x.Arg
	}
	return ""
}

func (x *Keyword) GetValue() *Node {
	if x != nil {
		return x.Value
	}
	return nil
}

type Module struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Body          []*Node                `protobuf:"bytes,1,rep,name=body,proto3" json:"body,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Module) Reset() {
	*x = Module{}
	mi := &file_ast_ast_proto_msgTypes[27]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Module) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Module) ProtoMessage() {}

func (x *Module) ProtoReflect() protoreflect.Message {
	mi := &file_ast_ast_proto_msgTypes[27]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Module.ProtoReflect.Descriptor instead.
func (*Module) Descriptor() ([]byte, []int) {
	return file_ast_ast_proto_rawDescGZIP(), []int{27}
}

func (x *Module) GetBody() []*Node {
	if x != nil {
		return x.Body
	}
	return nil
}

type Name struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Name) Reset() {
	*x = Name{}
	mi := &file_ast_ast_proto_msgTypes[28]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Name) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Name) ProtoMessage() {}

func (x *Name) ProtoReflect() protoreflect.Message {
	mi := &file_ast_ast_proto_msgTypes[28]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Name.ProtoReflect.Descriptor instead.
func (*Name) Descriptor() ([]byte, []int) {
	return file_ast_ast_proto_rawDescGZIP(), []int{28}
}

func (x *Name) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

type Pass struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Pass) Reset() {
	*x = Pass{}
	mi := &file_ast_ast_proto_msgTypes[29]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Pass) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Pass) ProtoMessage() {}

func (x *Pass) ProtoReflect() protoreflect.Message {
	mi := &file_ast_ast_proto_msgTypes[29]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Pass.ProtoReflect.Descriptor instead.
func (*Pass) Descriptor() ([]byte, []int) {
	return file_ast_ast_proto_rawDescGZIP(), []int{29}
}

type Return struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Value         *Node                  `protobuf:"bytes,1,opt,name=value,proto3" json:"value,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Return) Reset() {
	*x = Return{}
	mi := &file_ast_ast_proto_msgTypes[30]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Return) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Return) ProtoMessage() {}

func (x *Return) ProtoReflect() protoreflect.Message {
	mi := &file_ast_ast_proto_msgTypes[30]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Return.ProtoReflect.Descriptor instead.
func (*Return) Descriptor() ([]byte, []int) {
	return file_ast_ast_proto_rawDescGZIP(), []int{30}
}

func (x *Return) GetValue() *Node {
	if x != nil {
		return x.Value
	}
	return nil
}

type Subscript struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Value         *Name                  `protobuf:"bytes,1,opt,name=value,proto3" json:"value,omitempty"`
	Slice         *Node                  `protobuf:"bytes,2,opt,name=slice,proto3" json:"slice,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Subscript) Reset() {
	*x = Subscript{}
	mi := &file_ast_ast_proto_msgTypes[31]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Subscript) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Subscript) ProtoMessage() {}

func (x *Subscript) ProtoReflect() protoreflect.Message {
	mi := &file_ast_ast_proto_msgTypes[31]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Subscript.ProtoReflect.Descriptor instead.
func (*Subscript) Descriptor() ([]byte, []int) {
	return file_ast_ast_proto_rawDescGZIP(), []int{31}
}

func (x *Subscript) GetValue() *Name {
	if x != nil {
		return x.Value
	}
	return nil
}

func (x *Subscript) GetSlice() *Node {
	if x != nil {
		return x.Slice
	}
	return nil
}

type Yield struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Value         *Node                  `protobuf:"bytes,1,opt,name=value,proto3" json:"value,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Yield) Reset() {
	*x = Yield{}
	mi := &file_ast_ast_proto_msgTypes[32]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Yield) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Yield) ProtoMessage() {}

func (x *Yield) ProtoReflect() protoreflect.Message {
	mi := &file_ast_ast_proto_msgTypes[32]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Yield.ProtoReflect.Descriptor instead.
func (*Yield) Descriptor() ([]byte, []int) {
	return file_ast_ast_proto_rawDescGZIP(), []int{32}
}

func (x *Yield) GetValue() *Node {
	if x != nil {
		return x.Value
	}
	return nil
}

var File_ast_ast_proto protoreflect.FileDescriptor

const file_ast_ast_proto_rawDesc = "" +
	"\n" +
	"\rast/ast.proto\x12\x03ast\"\xa8\n" +
	"\n" +
	"\x04Node\x12,\n" +
	"\tclass_def\x18\x01 \x01(\v2\r.ast.ClassDefH\x00R\bClassDef\x12%\n" +
	"\x06import\x18\x02 \x01(\v2\v.ast.ImportH\x00R\x06Import\x122\n" +
	"\vimport_from\x18\x03 \x01(\v2\x0f.ast.ImportFromH\x00R\n" +
	"ImportFrom\x12%\n" +
	"\x06module\x18\x04 \x01(\v2\v.ast.ModuleH\x00R\x06Module\x12\"\n" +
	"\x05alias\x18\x05 \x01(\v2\n" +
	".ast.AliasH\x00R\x05Alias\x12/\n" +
	"\n" +
	"ann_assign\x18\x06 \x01(\v2\x0e.ast.AnnAssignH\x00R\tAnnAssign\x12\x1f\n" +
	"\x04name\x18\a \x01(\v2\t.ast.NameH\x00R\x04Name\x12.\n" +
	"\tsubscript\x18\b \x01(\v2\x0e.ast.SubscriptH\x00R\tSubscript\x12.\n" +
	"\tattribute\x18\t \x01(\v2\x0e.ast.AttributeH\x00R\tAttribute\x12+\n" +
	"\bconstant\x18\n" +
	" \x01(\v2\r.ast.ConstantH\x00R\bConstant\x12%\n" +
	"\x06assign\x18\v \x01(\v2\v.ast.AssignH\x00R\x06Assign\x12(\n" +
	"\acomment\x18\f \x01(\v2\f.ast.CommentH\x00R\aComment\x12\x1f\n" +
	"\x04expr\x18\r \x01(\v2\t.ast.ExprH\x00R\x04Expr\x12\x1f\n" +
	"\x04call\x18\x0e \x01(\v2\t.ast.CallH\x00R\x04Call\x125\n" +
	"\ffunction_def\x18\x0f \x01(\v2\x10.ast.FunctionDefH\x00R\vFunctionDef\x12\x1c\n" +
	"\x03arg\x18\x10 \x01(\v2\b.ast.ArgH\x00R\x03Arg\x12.\n" +
	"\targuments\x18\x11 \x01(\v2\x0e.ast.ArgumentsH\x00R\tArguments\x12E\n" +
	"\x12async_function_def\x18\x12 \x01(\v2\x15.ast.AsyncFunctionDefH\x00R\x10AsyncFunctionDef\x12\x1f\n" +
	"\x04pass\x18\x13 \x01(\v2\t.ast.PassH\x00R\x04Pass\x12\x1f\n" +
	"\x04dict\x18\x14 \x01(\v2\t.ast.DictH\x00R\x04Dict\x12\x19\n" +
	"\x02if\x18\x15 \x01(\v2\a.ast.IfH\x00R\x02If\x12(\n" +
	"\acompare\x18\x16 \x01(\v2\f.ast.CompareH\x00R\aCompare\x12%\n" +
	"\x06return\x18\x17 \x01(\v2\v.ast.ReturnH\x00R\x06Return\x12\x19\n" +
	"\x02is\x18\x18 \x01(\v2\a.ast.IsH\x00R\x02Is\x12(\n" +
	"\akeyword\x18\x19 \x01(\v2\f.ast.KeywordH\x00R\aKeyword\x12\"\n" +
	"\x05yield\x18\x1a \x01(\v2\n" +
	".ast.YieldH\x00R\x05Yield\x12\x1c\n" +
	"\x03for\x18\x1b \x01(\v2\b.ast.ForH\x00R\x03For\x12\"\n" +
	"\x05await\x18\x1c \x01(\v2\n" +
	".ast.AwaitH\x00R\x05Await\x12,\n" +
	"\tasync_for\x18\x1d \x01(\v2\r.ast.AsyncForH\x00R\bAsyncFor\x125\n" +
	"\fimport_group\x18\x1e \x01(\v2\x10.ast.ImportGroupH\x00R\vImportGroup\x12#\n" +
	"\x06bin_op\x18\x1f \x01(\v2\n" +
	".ast.BinOpH\x00R\x05BinOp\x12#\n" +
	"\x06bit_or\x18  \x01(\v2\n" +
	".ast.BitOrH\x00R\x05BitOrB\x06\n" +
	"\x04node\"\x1b\n" +
	"\x05Alias\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\"(\n" +
	"\x05Await\x12\x1f\n" +
	"\x05value\x18\x01 \x01(\v2\t.ast.NodeR\x05value\"b\n" +
	"\x05BinOp\x12\x1d\n" +
	"\x04left\x18\x01 \x01(\v2\t.ast.NodeR\x04left\x12\x19\n" +
	"\x02op\x18\x02 \x01(\v2\t.ast.NodeR\x02op\x12\x1f\n" +
	"\x05right\x18\x03 \x01(\v2\t.ast.NodeR\x05right\"\a\n" +
	"\x05BitOr\"@\n" +
	"\tAttribute\x12\x1f\n" +
	"\x05value\x18\x01 \x01(\v2\t.ast.NodeR\x05value\x12\x12\n" +
	"\x04attr\x18\x02 \x01(\tR\x04attr\"\x8b\x01\n" +
	"\tAnnAssign\x12!\n" +
	"\x06target\x18\x01 \x01(\v2\t.ast.NameR\x06target\x12)\n" +
	"\n" +
	"annotation\x18\x02 \x01(\v2\t.ast.NodeR\n" +
	"annotation\x12\x16\n" +
	"\x06simple\x18\x03 \x01(\x05R\x06simple\x12\x18\n" +
	"\aComment\x18\x04 \x01(\tR\acomment\"B\n" +
	"\x03Arg\x12\x10\n" +
	"\x03arg\x18\x01 \x01(\tR\x03arg\x12)\n" +
	"\n" +
	"annotation\x18\x02 \x01(\v2\t.ast.NodeR\n" +
	"annotation\"U\n" +
	"\tArguments\x12\x1c\n" +
	"\x04args\x18\x01 \x03(\v2\b.ast.ArgR\x04args\x12*\n" +
	"\fkw_only_args\x18\x02 \x03(\v2\b.ast.ArgR\n" +
	"kwonlyargs\"k\n" +
	"\bAsyncFor\x12!\n" +
	"\x06target\x18\x01 \x01(\v2\t.ast.NodeR\x06target\x12\x1d\n" +
	"\x04iter\x18\x02 \x01(\v2\t.ast.NodeR\x04iter\x12\x1d\n" +
	"\x04body\x18\x03 \x03(\v2\t.ast.NodeR\x04body\"\x8e\x01\n" +
	"\x10AsyncFunctionDef\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12\"\n" +
	"\x04Args\x18\x02 \x01(\v2\x0e.ast.ArgumentsR\x04args\x12\x1d\n" +
	"\x04body\x18\x03 \x03(\v2\t.ast.NodeR\x04body\x12#\n" +
	"\areturns\x18\x04 \x01(\v2\t.ast.NodeR\areturns\"h\n" +
	"\x06Assign\x12#\n" +
	"\atargets\x18\x01 \x03(\v2\t.ast.NodeR\atargets\x12\x1f\n" +
	"\x05value\x18\x02 \x01(\v2\t.ast.NodeR\x05value\x12\x18\n" +
	"\aComment\x18\x03 \x01(\tR\acomment\"n\n" +
	"\x04Call\x12\x1d\n" +
	"\x04func\x18\x01 \x01(\v2\t.ast.NodeR\x04func\x12\x1d\n" +
	"\x04args\x18\x02 \x03(\v2\t.ast.NodeR\x04args\x12(\n" +
	"\bkeywords\x18\x03 \x03(\v2\f.ast.KeywordR\bkeywords\"\xb8\x01\n" +
	"\bClassDef\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12\x1f\n" +
	"\x05bases\x18\x02 \x03(\v2\t.ast.NodeR\x05bases\x12%\n" +
	"\bkeywords\x18\x03 \x03(\v2\t.ast.NodeR\bkeywords\x12\x1d\n" +
	"\x04body\x18\x04 \x03(\v2\t.ast.NodeR\x04body\x121\n" +
	"\x0edecorator_list\x18\x05 \x03(\v2\t.ast.NodeR\x0edecorator_list\"\x1d\n" +
	"\aComment\x12\x12\n" +
	"\x04text\x18\x01 \x01(\tR\x04text\"r\n" +
	"\aCompare\x12\x1d\n" +
	"\x04left\x18\x01 \x01(\v2\t.ast.NodeR\x04left\x12\x1b\n" +
	"\x03ops\x18\x02 \x03(\v2\t.ast.NodeR\x03ops\x12+\n" +
	"\vcomparators\x18\x03 \x03(\v2\t.ast.NodeR\vcomparators\"T\n" +
	"\bConstant\x12\x15\n" +
	"\x03str\x18\x01 \x01(\tH\x00R\x06string\x12\x12\n" +
	"\x03int\x18\x02 \x01(\x05H\x00R\x03int\x12\x14\n" +
	"\x04none\x18\x03 \x01(\bH\x00R\x04noneB\a\n" +
	"\x05value\"H\n" +
	"\x04Dict\x12\x1d\n" +
	"\x04keys\x18\x01 \x03(\v2\t.ast.NodeR\x04keys\x12!\n" +
	"\x06values\x18\x02 \x03(\v2\t.ast.NodeR\x06values\"'\n" +
	"\x04Expr\x12\x1f\n" +
	"\x05value\x18\x01 \x01(\v2\t.ast.NodeR\x05value\"f\n" +
	"\x03For\x12!\n" +
	"\x06target\x18\x01 \x01(\v2\t.ast.NodeR\x06target\x12\x1d\n" +
	"\x04iter\x18\x02 \x01(\v2\t.ast.NodeR\x04iter\x12\x1d\n" +
	"\x04body\x18\x03 \x03(\v2\t.ast.NodeR\x04body\"\x89\x01\n" +
	"\vFunctionDef\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12\"\n" +
	"\x04Args\x18\x02 \x01(\v2\x0e.ast.ArgumentsR\x04args\x12\x1d\n" +
	"\x04body\x18\x03 \x03(\v2\t.ast.NodeR\x04body\x12#\n" +
	"\areturns\x18\x04 \x01(\v2\t.ast.NodeR\areturns\"f\n" +
	"\x02If\x12\x1d\n" +
	"\x04test\x18\x01 \x01(\v2\t.ast.NodeR\x04test\x12\x1d\n" +
	"\x04body\x18\x02 \x03(\v2\t.ast.NodeR\x04body\x12\"\n" +
	"\aor_else\x18\x03 \x03(\v2\t.ast.NodeR\x06orelse\")\n" +
	"\x06Import\x12\x1f\n" +
	"\x05names\x18\x01 \x03(\v2\t.ast.NodeR\x05names\"[\n" +
	"\n" +
	"ImportFrom\x12\x16\n" +
	"\x06module\x18\x01 \x01(\tR\x06module\x12\x1f\n" +
	"\x05names\x18\x02 \x03(\v2\t.ast.NodeR\x05names\x12\x14\n" +
	"\x05level\x18\x03 \x01(\x05R\x05level\"2\n" +
	"\vImportGroup\x12#\n" +
	"\aimports\x18\x01 \x03(\v2\t.ast.NodeR\aimports\"\x04\n" +
	"\x02Is\"<\n" +
	"\aKeyword\x12\x10\n" +
	"\x03arg\x18\x01 \x01(\tR\x03arg\x12\x1f\n" +
	"\x05value\x18\x02 \x01(\v2\t.ast.NodeR\x05value\"'\n" +
	"\x06Module\x12\x1d\n" +
	"\x04body\x18\x01 \x03(\v2\t.ast.NodeR\x04body\"\x16\n" +
	"\x04Name\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\"\x06\n" +
	"\x04Pass\")\n" +
	"\x06Return\x12\x1f\n" +
	"\x05value\x18\x01 \x01(\v2\t.ast.NodeR\x05value\"M\n" +
	"\tSubscript\x12\x1f\n" +
	"\x05value\x18\x01 \x01(\v2\t.ast.NameR\x05value\x12\x1f\n" +
	"\x05slice\x18\x02 \x01(\v2\t.ast.NodeR\x05slice\"(\n" +
	"\x05Yield\x12\x1f\n" +
	"\x05value\x18\x01 \x01(\v2\t.ast.NodeR\x05valueB2Z0github.com/sqlc-dev/sqlc-gen-python/internal/astb\x06proto3"

var (
	file_ast_ast_proto_rawDescOnce sync.Once
	file_ast_ast_proto_rawDescData []byte
)

func file_ast_ast_proto_rawDescGZIP() []byte {
	file_ast_ast_proto_rawDescOnce.Do(func() {
		file_ast_ast_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_ast_ast_proto_rawDesc), len(file_ast_ast_proto_rawDesc)))
	})
	return file_ast_ast_proto_rawDescData
}

var file_ast_ast_proto_msgTypes = make([]protoimpl.MessageInfo, 33)
var file_ast_ast_proto_goTypes = []any{
	(*Node)(nil),             // 0: ast.Node
	(*Alias)(nil),            // 1: ast.Alias
	(*Await)(nil),            // 2: ast.Await
	(*BinOp)(nil),            // 3: ast.BinOp
	(*BitOr)(nil),            // 4: ast.BitOr
	(*Attribute)(nil),        // 5: ast.Attribute
	(*AnnAssign)(nil),        // 6: ast.AnnAssign
	(*Arg)(nil),              // 7: ast.Arg
	(*Arguments)(nil),        // 8: ast.Arguments
	(*AsyncFor)(nil),         // 9: ast.AsyncFor
	(*AsyncFunctionDef)(nil), // 10: ast.AsyncFunctionDef
	(*Assign)(nil),           // 11: ast.Assign
	(*Call)(nil),             // 12: ast.Call
	(*ClassDef)(nil),         // 13: ast.ClassDef
	(*Comment)(nil),          // 14: ast.Comment
	(*Compare)(nil),          // 15: ast.Compare
	(*Constant)(nil),         // 16: ast.Constant
	(*Dict)(nil),             // 17: ast.Dict
	(*Expr)(nil),             // 18: ast.Expr
	(*For)(nil),              // 19: ast.For
	(*FunctionDef)(nil),      // 20: ast.FunctionDef
	(*If)(nil),               // 21: ast.If
	(*Import)(nil),           // 22: ast.Import
	(*ImportFrom)(nil),       // 23: ast.ImportFrom
	(*ImportGroup)(nil),      // 24: ast.ImportGroup
	(*Is)(nil),               // 25: ast.Is
	(*Keyword)(nil),          // 26: ast.Keyword
	(*Module)(nil),           // 27: ast.Module
	(*Name)(nil),             // 28: ast.Name
	(*Pass)(nil),             // 29: ast.Pass
	(*Return)(nil),           // 30: ast.Return
	(*Subscript)(nil),        // 31: ast.Subscript
	(*Yield)(nil),            // 32: ast.Yield
}
var file_ast_ast_proto_depIdxs = []int32{
	13, // 0: ast.Node.class_def:type_name -> ast.ClassDef
	22, // 1: ast.Node.import:type_name -> ast.Import
	23, // 2: ast.Node.import_from:type_name -> ast.ImportFrom
	27, // 3: ast.Node.module:type_name -> ast.Module
	1,  // 4: ast.Node.alias:type_name -> ast.Alias
	6,  // 5: ast.Node.ann_assign:type_name -> ast.AnnAssign
	28, // 6: ast.Node.name:type_name -> ast.Name
	31, // 7: ast.Node.subscript:type_name -> ast.Subscript
	5,  // 8: ast.Node.attribute:type_name -> ast.Attribute
	16, // 9: ast.Node.constant:type_name -> ast.Constant
	11, // 10: ast.Node.assign:type_name -> ast.Assign
	14, // 11: ast.Node.comment:type_name -> ast.Comment
	18, // 12: ast.Node.expr:type_name -> ast.Expr
	12, // 13: ast.Node.call:type_name -> ast.Call
	20, // 14: ast.Node.function_def:type_name -> ast.FunctionDef
	7,  // 15: ast.Node.arg:type_name -> ast.Arg
	8,  // 16: ast.Node.arguments:type_name -> ast.Arguments
	10, // 17: ast.Node.async_function_def:type_name -> ast.AsyncFunctionDef
	29, // 18: ast.Node.pass:type_name -> ast.Pass
	17, // 19: ast.Node.dict:type_name -> ast.Dict
	21, // 20: ast.Node.if:type_name -> ast.If
	15, // 21: ast.Node.compare:type_name -> ast.Compare
	30, // 22: ast.Node.return:type_name -> ast.Return
	25, // 23: ast.Node.is:type_name -> ast.Is
	26, // 24: ast.Node.keyword:type_name -> ast.Keyword
	32, // 25: ast.Node.yield:type_name -> ast.Yield
	19, // 26: ast.Node.for:type_name -> ast.For
	2,  // 27: ast.Node.await:type_name -> ast.Await
	9,  // 28: ast.Node.async_for:type_name -> ast.AsyncFor
	24, // 29: ast.Node.import_group:type_name -> ast.ImportGroup
	3,  // 30: ast.Node.bin_op:type_name -> ast.BinOp
	4,  // 31: ast.Node.bit_or:type_name -> ast.BitOr
	0,  // 32: ast.Await.value:type_name -> ast.Node
	0,  // 33: ast.BinOp.left:type_name -> ast.Node
	0,  // 34: ast.BinOp.op:type_name -> ast.Node
	0,  // 35: ast.BinOp.right:type_name -> ast.Node
	0,  // 36: ast.Attribute.value:type_name -> ast.Node
	28, // 37: ast.AnnAssign.target:type_name -> ast.Name
	0,  // 38: ast.AnnAssign.annotation:type_name -> ast.Node
	0,  // 39: ast.Arg.annotation:type_name -> ast.Node
	7,  // 40: ast.Arguments.args:type_name -> ast.Arg
	7,  // 41: ast.Arguments.kw_only_args:type_name -> ast.Arg
	0,  // 42: ast.AsyncFor.target:type_name -> ast.Node
	0,  // 43: ast.AsyncFor.iter:type_name -> ast.Node
	0,  // 44: ast.AsyncFor.body:type_name -> ast.Node
	8,  // 45: ast.AsyncFunctionDef.Args:type_name -> ast.Arguments
	0,  // 46: ast.AsyncFunctionDef.body:type_name -> ast.Node
	0,  // 47: ast.AsyncFunctionDef.returns:type_name -> ast.Node
	0,  // 48: ast.Assign.targets:type_name -> ast.Node
	0,  // 49: ast.Assign.value:type_name -> ast.Node
	0,  // 50: ast.Call.func:type_name -> ast.Node
	0,  // 51: ast.Call.args:type_name -> ast.Node
	26, // 52: ast.Call.keywords:type_name -> ast.Keyword
	0,  // 53: ast.ClassDef.bases:type_name -> ast.Node
	0,  // 54: ast.ClassDef.keywords:type_name -> ast.Node
	0,  // 55: ast.ClassDef.body:type_name -> ast.Node
	0,  // 56: ast.ClassDef.decorator_list:type_name -> ast.Node
	0,  // 57: ast.Compare.left:type_name -> ast.Node
	0,  // 58: ast.Compare.ops:type_name -> ast.Node
	0,  // 59: ast.Compare.comparators:type_name -> ast.Node
	0,  // 60: ast.Dict.keys:type_name -> ast.Node
	0,  // 61: ast.Dict.values:type_name -> ast.Node
	0,  // 62: ast.Expr.value:type_name -> ast.Node
	0,  // 63: ast.For.target:type_name -> ast.Node
	0,  // 64: ast.For.iter:type_name -> ast.Node
	0,  // 65: ast.For.body:type_name -> ast.Node
	8,  // 66: ast.FunctionDef.Args:type_name -> ast.Arguments
	0,  // 67: ast.FunctionDef.body:type_name -> ast.Node
	0,  // 68: ast.FunctionDef.returns:type_name -> ast.Node
	0,  // 69: ast.If.test:type_name -> ast.Node
	0,  // 70: ast.If.body:type_name -> ast.Node
	0,  // 71: ast.If.or_else:type_name -> ast.Node
	0,  // 72: ast.Import.names:type_name -> ast.Node
	0,  // 73: ast.ImportFrom.names:type_name -> ast.Node
	0,  // 74: ast.ImportGroup.imports:type_name -> ast.Node
	0,  // 75: ast.Keyword.value:type_name -> ast.Node
	0,  // 76: ast.Module.body:type_name -> ast.Node
	0,  // 77: ast.Return.value:type_name -> ast.Node
	28, // 78: ast.Subscript.value:type_name -> ast.Name
	0,  // 79: ast.Subscript.slice:type_name -> ast.Node
	0,  // 80: ast.Yield.value:type_name -> ast.Node
	81, // [81:81] is the sub-list for method output_type
	81, // [81:81] is the sub-list for method input_type
	81, // [81:81] is the sub-list for extension type_name
	81, // [81:81] is the sub-list for extension extendee
	0,  // [0:81] is the sub-list for field type_name
}

func init() { file_ast_ast_proto_init() }
func file_ast_ast_proto_init() {
	if File_ast_ast_proto != nil {
		return
	}
	file_ast_ast_proto_msgTypes[0].OneofWrappers = []any{
		(*Node_ClassDef)(nil),
		(*Node_Import)(nil),
		(*Node_ImportFrom)(nil),
		(*Node_Module)(nil),
		(*Node_Alias)(nil),
		(*Node_AnnAssign)(nil),
		(*Node_Name)(nil),
		(*Node_Subscript)(nil),
		(*Node_Attribute)(nil),
		(*Node_Constant)(nil),
		(*Node_Assign)(nil),
		(*Node_Comment)(nil),
		(*Node_Expr)(nil),
		(*Node_Call)(nil),
		(*Node_FunctionDef)(nil),
		(*Node_Arg)(nil),
		(*Node_Arguments)(nil),
		(*Node_AsyncFunctionDef)(nil),
		(*Node_Pass)(nil),
		(*Node_Dict)(nil),
		(*Node_If)(nil),
		(*Node_Compare)(nil),
		(*Node_Return)(nil),
		(*Node_Is)(nil),
		(*Node_Keyword)(nil),
		(*Node_Yield)(nil),
		(*Node_For)(nil),
		(*Node_Await)(nil),
		(*Node_AsyncFor)(nil),
		(*Node_ImportGroup)(nil),
		(*Node_BinOp)(nil),
		(*Node_BitOr)(nil),
	}
	file_ast_ast_proto_msgTypes[16].OneofWrappers = []any{
		(*Constant_Str)(nil),
		(*Constant_Int)(nil),
		(*Constant_None)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_ast_ast_proto_rawDesc), len(file_ast_ast_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   33,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_ast_ast_proto_goTypes,
		DependencyIndexes: file_ast_ast_proto_depIdxs,
		MessageInfos:      file_ast_ast_proto_msgTypes,
	}.Build()
	File_ast_ast_proto = out.File
	file_ast_ast_proto_goTypes = nil
	file_ast_ast_proto_depIdxs = nil
}
