# Code generated by sqlc. DO NOT EDIT.
# versions:
#   sqlc v1.30.0
import sqlalchemy.exc


class QueryError(Exception):
    """Base class for all query errors."""

    def __init__(self, message: str, query_name: str, cause: Exception | None = None):
        super().__init__(message)
        self.query_name = query_name
        self.cause = cause


class UniqueViolationError(QueryError):
    """Raised on unique constraint violation (PG 23505)."""

    pass


class ForeignKeyViolationError(QueryError):
    """Raised on foreign key constraint violation (PG 23503)."""

    pass


class CheckViolationError(QueryError):
    """Raised on check constraint violation (PG 23514)."""

    pass


class NotNullViolationError(QueryError):
    """Raised on not-null constraint violation (PG 23502)."""

    pass


class ExclusionViolationError(QueryError):
    """Raised on exclusion constraint violation (PG 23P01)."""

    pass


def _wrap_integrity_error(
    e: sqlalchemy.exc.IntegrityError, query_name: str
) -> QueryError:
    pgcode = getattr(e.orig, "pgcode", None) or getattr(e.orig, "sqlstate", None)
    if pgcode == "23505":
        return UniqueViolationError(str(e), query_name, cause=e)
    if pgcode == "23503":
        return ForeignKeyViolationError(str(e), query_name, cause=e)
    if pgcode == "23514":
        return CheckViolationError(str(e), query_name, cause=e)
    if pgcode == "23502":
        return NotNullViolationError(str(e), query_name, cause=e)
    if pgcode == "23P01":
        return ExclusionViolationError(str(e), query_name, cause=e)
    return QueryError(str(e), query_name, cause=e)
