# Code generated by sqlc. DO NOT EDIT.
# versions:
#   sqlc v1.30.0
# source: query.sql
from typing import cast

import sqlalchemy
import sqlalchemy.exc
import sqlalchemy.ext.asyncio
import sqlalchemy.orm

from querytest import errors
from querytest import models


CREATE_AUTHOR = """-- name: create_author \\:one
INSERT INTO authors (name, bio) VALUES (:p1, :p2) RETURNING id, name, bio
"""


DELETE_AUTHOR = """-- name: delete_author \\:exec
DELETE FROM authors WHERE id = :p1
"""


GET_AUTHOR = """-- name: get_author \\:one
SELECT id, name, bio FROM authors WHERE id = :p1
"""


class Querier[T: sqlalchemy.engine.Connection | sqlalchemy.orm.Session]:
    _conn: T

    def __init__(self, conn: T):
        self._conn = conn

    def create_author(self, *, name: str, bio: str | None) -> models.Author | None:
        try:
            row = self._conn.execute(sqlalchemy.text(CREATE_AUTHOR), {"p1": name, "p2": bio}).first()
        except sqlalchemy.exc.IntegrityError as e:
            raise errors._wrap_integrity_error(e, "create_author") from e
        except sqlalchemy.exc.OperationalError as e:
            raise errors._wrap_operational_error(e, "create_author") from e
        if row is None:
            return None
        return models.Author(
            id=cast(int, row[0]),
            name=cast(str, row[1]),
            bio=cast(str | None, row[2]),
        )

    def delete_author(self, *, id: int) -> None:
        try:
            _ = self._conn.execute(sqlalchemy.text(DELETE_AUTHOR), {"p1": id})
        except sqlalchemy.exc.IntegrityError as e:
            raise errors._wrap_integrity_error(e, "delete_author") from e
        except sqlalchemy.exc.OperationalError as e:
            raise errors._wrap_operational_error(e, "delete_author") from e

    def get_author(self, *, id: int) -> models.Author | None:
        try:
            row = self._conn.execute(sqlalchemy.text(GET_AUTHOR), {"p1": id}).first()
        except sqlalchemy.exc.IntegrityError as e:
            raise errors._wrap_integrity_error(e, "get_author") from e
        except sqlalchemy.exc.OperationalError as e:
            raise errors._wrap_operational_error(e, "get_author") from e
        if row is None:
            return None
        return models.Author(
            id=cast(int, row[0]),
            name=cast(str, row[1]),
            bio=cast(str | None, row[2]),
        )


class AsyncQuerier[T: sqlalchemy.ext.asyncio.AsyncConnection | sqlalchemy.ext.asyncio.AsyncSession]:
    _conn: T

    def __init__(self, conn: T):
        self._conn = conn

    async def create_author(self, *, name: str, bio: str | None) -> models.Author | None:
        try:
            row = (await self._conn.execute(sqlalchemy.text(CREATE_AUTHOR), {"p1": name, "p2": bio})).first()
        except sqlalchemy.exc.IntegrityError as e:
            raise errors._wrap_integrity_error(e, "create_author") from e
        except sqlalchemy.exc.OperationalError as e:
            raise errors._wrap_operational_error(e, "create_author") from e
        if row is None:
            return None
        return models.Author(
            id=cast(int, row[0]),
            name=cast(str, row[1]),
            bio=cast(str | None, row[2]),
        )

    async def delete_author(self, *, id: int) -> None:
        try:
            _ = await self._conn.execute(sqlalchemy.text(DELETE_AUTHOR), {"p1": id})
        except sqlalchemy.exc.IntegrityError as e:
            raise errors._wrap_integrity_error(e, "delete_author") from e
        except sqlalchemy.exc.OperationalError as e:
            raise errors._wrap_operational_error(e, "delete_author") from e

    async def get_author(self, *, id: int) -> models.Author | None:
        try:
            row = (await self._conn.execute(sqlalchemy.text(GET_AUTHOR), {"p1": id})).first()
        except sqlalchemy.exc.IntegrityError as e:
            raise errors._wrap_integrity_error(e, "get_author") from e
        except sqlalchemy.exc.OperationalError as e:
            raise errors._wrap_operational_error(e, "get_author") from e
        if row is None:
            return None
        return models.Author(
            id=cast(int, row[0]),
            name=cast(str, row[1]),
            bio=cast(str | None, row[2]),
        )
