# Code generated by sqlc. DO NOT EDIT.
# versions:
#   sqlc v1.30.0
# source: query.sql
from collections.abc import AsyncIterator, Iterator
from typing import cast
import typing

import sqlalchemy
import sqlalchemy.ext.asyncio
import sqlalchemy.orm

from querytest import models


GET_AUTHOR = """-- name: get_author \:one
SELECT id, name, bio FROM authors WHERE id = :p1
"""

LIST_AUTHORS = """-- name: list_authors \:many
SELECT id, name, bio FROM authors ORDER BY name
"""

CREATE_AUTHOR = """-- name: create_author \:exec
INSERT INTO authors (name, bio) VALUES (:p1, :p2)
"""

DELETE_AUTHOR = """-- name: delete_author \:execrows
DELETE FROM authors WHERE id = :p1
"""


class QuerierProtocol(typing.Protocol):
    def get_author(self, *, id: int) -> models.Author | None: ...

    def list_authors(self) -> Iterator[models.Author]: ...

    def create_author(self, *, name: str, bio: str | None) -> None: ...

    def delete_author(self, *, id: int) -> int: ...


class AsyncQuerierProtocol(typing.Protocol):
    async def get_author(self, *, id: int) -> models.Author | None: ...

    async def list_authors(self) -> AsyncIterator[models.Author]: ...

    async def create_author(self, *, name: str, bio: str | None) -> None: ...

    async def delete_author(self, *, id: int) -> int: ...


class Querier[T: sqlalchemy.engine.Connection | sqlalchemy.orm.Session]:
    _conn: T

    def __init__(self, conn: T):
        self._conn = conn

    def get_author(self, *, id: int) -> models.Author | None:
        row = self._conn.execute(sqlalchemy.text(GET_AUTHOR), {"p1": id}).first()
        if row is None:
            return None
        return models.Author(
            id=cast(int, row[0]),
            name=cast(str, row[1]),
            bio=cast(str | None, row[2]),
        )

    def list_authors(self) -> Iterator[models.Author]:
        result = self._conn.execute(sqlalchemy.text(LIST_AUTHORS))
        for row in result:
            yield models.Author(
                id=cast(int, row[0]),
                name=cast(str, row[1]),
                bio=cast(str | None, row[2]),
            )

    def create_author(self, *, name: str, bio: str | None) -> None:
        _ = self._conn.execute(sqlalchemy.text(CREATE_AUTHOR), {"p1": name, "p2": bio})

    def delete_author(self, *, id: int) -> int:
        result = self._conn.execute(sqlalchemy.text(DELETE_AUTHOR), {"p1": id})
        return result.rowcount


class AsyncQuerier[T: sqlalchemy.ext.asyncio.AsyncConnection | sqlalchemy.ext.asyncio.AsyncSession]:
    _conn: T

    def __init__(self, conn: T):
        self._conn = conn

    async def get_author(self, *, id: int) -> models.Author | None:
        row = (await self._conn.execute(sqlalchemy.text(GET_AUTHOR), {"p1": id})).first()
        if row is None:
            return None
        return models.Author(
            id=cast(int, row[0]),
            name=cast(str, row[1]),
            bio=cast(str | None, row[2]),
        )

    async def list_authors(self) -> AsyncIterator[models.Author]:
        result = await self._conn.stream(sqlalchemy.text(LIST_AUTHORS))
        async for row in result:
            yield models.Author(
                id=cast(int, row[0]),
                name=cast(str, row[1]),
                bio=cast(str | None, row[2]),
            )

    async def create_author(self, *, name: str, bio: str | None) -> None:
        _ = await self._conn.execute(sqlalchemy.text(CREATE_AUTHOR), {"p1": name, "p2": bio})

    async def delete_author(self, *, id: int) -> int:
        result = await self._conn.execute(sqlalchemy.text(DELETE_AUTHOR), {"p1": id})
        return result.rowcount
