# Code generated by sqlc. DO NOT EDIT.
# versions:
#   sqlc v1.30.0
import pydantic
from typing import Any
import uuid

import my_lib.models


class Article(pydantic.BaseModel):
    id: int
    metadata: my_lib.models.ArticleMetadata
    settings: Any | None
    author_id: uuid.UUID
