# Code generated by sqlc. DO NOT EDIT.
# versions:
#   sqlc v1.30.0
# source: query.sql
from typing import Any, cast
import uuid

import my_lib.models
import sqlalchemy
import sqlalchemy.orm

from python import models


CREATE_ARTICLE = """-- name: create_article \\:one
INSERT INTO articles (metadata, settings, author_id)
VALUES (:p1, :p2, :p3)
RETURNING id, metadata, settings, author_id
"""


GET_ARTICLE = """-- name: get_article \\:one
SELECT id, metadata, settings, author_id FROM articles WHERE id = :p1
"""


class Querier[T: sqlalchemy.engine.Connection | sqlalchemy.orm.Session]:
    _conn: T

    def __init__(self, conn: T):
        self._conn = conn

    def create_article(self, *, metadata: my_lib.models.ArticleMetadata, settings: Any | None, author_id: uuid.UUID) -> models.Article | None:
        row = self._conn.execute(sqlalchemy.text(CREATE_ARTICLE), {"p1": metadata, "p2": settings, "p3": author_id}).first()
        if row is None:
            return None
        return models.Article(
            id=cast(int, row[0]),
            metadata=cast(my_lib.models.ArticleMetadata, row[1]),
            settings=cast(Any | None, row[2]),
            author_id=cast(uuid.UUID, row[3]),
        )

    def get_article(self, *, id: int) -> models.Article | None:
        row = self._conn.execute(sqlalchemy.text(GET_ARTICLE), {"p1": id}).first()
        if row is None:
            return None
        return models.Article(
            id=cast(int, row[0]),
            metadata=cast(my_lib.models.ArticleMetadata, row[1]),
            settings=cast(Any | None, row[2]),
            author_id=cast(uuid.UUID, row[3]),
        )
