# Code generated by sqlc. DO NOT EDIT.
# versions:
#   sqlc v1.30.0
# source: query.sql
from collections.abc import Iterator
from typing import cast

import sqlalchemy
import sqlalchemy.orm

from python import models


CREATE_USER = """-- name: create_user \\:one
INSERT INTO users (name, email, age, created_at)
VALUES (:p1, :p2, :p3, :p4)
RETURNING id, name, email, age, created_at
"""


GET_USER = """-- name: get_user \\:one
SELECT id, name, email, age, created_at FROM users WHERE id = :p1
"""


LIST_USERS = """-- name: list_users \\:many
SELECT id, name, email, age, created_at FROM users ORDER BY id
"""


class Querier[T: sqlalchemy.engine.Connection | sqlalchemy.orm.Session]:
    _conn: T

    def __init__(self, conn: T):
        self._conn = conn

    def create_user(self, *, name: str, email: str | None, age: int | None, created_at: pydantic.AwareDatetime) -> models.User | None:
        row = self._conn.execute(sqlalchemy.text(CREATE_USER), {
            "p1": name,
            "p2": email,
            "p3": age,
            "p4": created_at,
        }).first()
        if row is None:
            return None
        return models.User(
            id=cast(int, row[0]),
            name=cast(str, row[1]),
            email=cast(str | None, row[2]),
            age=cast(int | None, row[3]),
            created_at=cast(pydantic.AwareDatetime, row[4]),
        )

    def get_user(self, *, id: int) -> models.User | None:
        row = self._conn.execute(sqlalchemy.text(GET_USER), {"p1": id}).first()
        if row is None:
            return None
        return models.User(
            id=cast(int, row[0]),
            name=cast(str, row[1]),
            email=cast(str | None, row[2]),
            age=cast(int | None, row[3]),
            created_at=cast(pydantic.AwareDatetime, row[4]),
        )

    def list_users(self) -> Iterator[models.User]:
        result = self._conn.execute(sqlalchemy.text(LIST_USERS))
        for row in result:
            yield models.User(
                id=cast(int, row[0]),
                name=cast(str, row[1]),
                email=cast(str | None, row[2]),
                age=cast(int | None, row[3]),
                created_at=cast(pydantic.AwareDatetime, row[4]),
            )
