# Code generated by sqlc. DO NOT EDIT.
# versions:
#   sqlc v1.30.0
import pydantic


class Item(pydantic.BaseModel):
    id: int
    class_: str | None
    import_: str | None
    def_: str | None
    pass_: str | None
    yield_: str | None
