# Code generated by sqlc. DO NOT EDIT.
# versions:
#   sqlc v1.30.0
# source: query.sql
import pydantic
from typing import cast

import sqlalchemy
import sqlalchemy.orm

from python import models


CREATE_ITEM = """-- name: create_item \\:one
INSERT INTO items (class, import, def, pass, yield)
VALUES (:p1, :p2, :p3, :p4, :p5)
RETURNING id, class, import, def, pass, yield
"""


class CreateItemParams(pydantic.BaseModel):
    class_: str | None
    import_: str | None
    def_: str | None
    pass_: str | None
    yield_: str | None


GET_ITEM_BY_CLASS = """-- name: get_item_by_class \\:one
SELECT id, class, import, def, pass, yield FROM items WHERE class = :p1
"""


class Querier[T: sqlalchemy.engine.Connection | sqlalchemy.orm.Session]:
    _conn: T

    def __init__(self, conn: T):
        self._conn = conn

    def create_item(self, arg: CreateItemParams) -> models.Item | None:
        row = self._conn.execute(sqlalchemy.text(CREATE_ITEM), {
            "p1": arg.class_,
            "p2": arg.import_,
            "p3": arg.def_,
            "p4": arg.pass_,
            "p5": arg.yield_,
        }).first()
        if row is None:
            return None
        return models.Item(
            id=cast(int, row[0]),
            class_=cast(str | None, row[1]),
            import_=cast(str | None, row[2]),
            def_=cast(str | None, row[3]),
            pass_=cast(str | None, row[4]),
            yield_=cast(str | None, row[5]),
        )

    def get_item_by_class(self, *, class_: str | None) -> models.Item | None:
        row = self._conn.execute(sqlalchemy.text(GET_ITEM_BY_CLASS), {"p1": class_}).first()
        if row is None:
            return None
        return models.Item(
            id=cast(int, row[0]),
            class_=cast(str | None, row[1]),
            import_=cast(str | None, row[2]),
            def_=cast(str | None, row[3]),
            pass_=cast(str | None, row[4]),
            yield_=cast(str | None, row[5]),
        )
