# Code generated by sqlc. DO NOT EDIT.
# versions:
#   sqlc v1.30.0
# source: query.sql
import dataclasses
from typing import cast

import sqlalchemy
import sqlalchemy.ext.asyncio
import sqlalchemy.orm

from querytest import models


CREATE_AUTHORS = """-- name: create_authors \\:batchexec
INSERT INTO authors (name, bio) VALUES (:p1, :p2)
"""


@dataclasses.dataclass()
class CreateAuthorsParams:
    name: str
    bio: str | None


class Querier[T: sqlalchemy.engine.Connection | sqlalchemy.orm.Session]:
    _conn: T

    def __init__(self, conn: T):
        self._conn = conn

    def create_authors(self, *, args: list[CreateAuthorsParams]) -> None:
        self._conn.execute(sqlalchemy.text(CREATE_AUTHORS), [{"p1": a.name, "p2": a.bio} for a in args])


class AsyncQuerier[T: sqlalchemy.ext.asyncio.AsyncConnection | sqlalchemy.ext.asyncio.AsyncSession]:
    _conn: T

    def __init__(self, conn: T):
        self._conn = conn

    async def create_authors(self, *, args: list[CreateAuthorsParams]) -> None:
        await self._conn.execute(sqlalchemy.text(CREATE_AUTHORS), [{"p1": a.name, "p2": a.bio} for a in args])
